service: hacksecure-utlity-serverless-functions

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2

functions:
  listMLH:
    handler: handlers.listMLH
    events:
      - http: GET /listMLH

plugins:
  - serverless-offline